from enum import StrEnum

class EventType(StrEnum):
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_DELAYED = "ORDER_DELAYED"

    SHIPMENT_CREATED = "SHIPMENT_CREATED"
    SHIPMENT_UPDATED = "SHIPMENT_UPDATED"
    SHIPMENT_DELIVERED = "SHIPMENT_DELIVERED"

    TICKET_CREATED = "TICKET_CREATED"
    TICKET_UPDATED = "TICKET_UPDATED"