"""add human approval queue

Revision ID: 44d340f27fe8
Revises: e69e0049899f
Create Date: 2026-09-05 10:17:06.112465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d340f27fe8'
down_revision: Union[str, Sequence[str], None] = 'e69e0049899f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to create table ###
    op.create_table(
        "human_approvals",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("event_id", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.Integer(), sa.ForeignKey("orders.id"), nullable=False),
        sa.Column("customer_id", sa.Integer(), sa.ForeignKey("customers.id"), nullable=False),
        sa.Column("agent_name", sa.String(length=50), nullable=False),
        sa.Column("decision", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default=sa.text("'PENDING'")),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=100), nullable=True),
    )
    op.create_index(op.f("ix_human_approvals_event_id"), "human_approvals", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted to drop table ###
    op.drop_index(op.f("ix_human_approvals_event_id"), table_name="human_approvals")
    op.drop_table("human_approvals")
    # ### end Alembic commands ###
